msimerson/Mail-Toaster-6

- mail-toaster.sh
- provision-avg.sh
- provision-clamav.sh
- provision-dns.sh
- provision-haraka.sh
- provision-host.sh
- provision-rspamd.sh
- provision-spamassassin.sh
- provision-webmail.sh
* when promoting a jail, clear shared IPC
* avg: try to d/l virus dbs when installing
* mount fdescfs and procfs
* clamav:
* prompt for installation of ClamAV Unofficial
* match my production settings
* dns
* listen on all IPv6 and IPv4 addresses
* hide identity & version
* rspamd: enable dmarc report storage in redis
* haraka: update more plugins:
* spamassassin, watch, geoip, and p0f (upstream bug fixes)
* webmail:
* TLS config updates for squirrelmail
* tell php where ssl ca certs are
* spamassassin: added bayes_ignore_header rules
> stronger settings for clamav

- provision-host.sh
* syslogd can't be found to 172 yet, b/c lo1 isn't provisioned, but it can't be listening either or the listener test fails. Temp disable listener.
* if `portsnap update` fails, try `portsnap extract` before bailing out
> disable syslog global listener

- mail-toaster.sh
- provision-haproxy.sh
* enables local customizations to be preserved across provisions
> haproxy: use data dir for haproxy.conf and ssl

- .gitignore
- mail-toaster.sh
- stores local config settings in mail-toaster.conf
Checklist:
> save config in mail-toaster.conf

- mail-toaster.sh
- provision-mysql.sh
- Add the option to install MariaDB, decided to add an extra ENV var, since the TOASTER_MYSQL is used in multiple provision, would mean lot more code changes and no backward compatibility
-
-
Fixes # .
Checklist:
> Add the option to install MariaDB

- mail-toaster.sh
- provision-avg.sh
- provision-clamav.sh
- provision-dovecot.sh
- provision-dspam.sh
- provision-elasticsearch.sh
- provision-haproxy.sh
- provision-haraka.sh
- provision-joomla.sh
- provision-memcached.sh
- provision-minecraft.sh
- provision-mysql.sh
- provision-nginx.sh
- provision-php7.sh
- provision-redis.sh
- provision-rspamd.sh
- provision-spamassassin.sh
- provision-vpopmail.sh
- provision-webmail.sh
* refactor many sockstat ... calls into stage_listening $port_num
* replace sockstat -l | grep NUM  with sockstat -p NUM
* add -6 to sockstat, so IPv6 only listeners will work
> refactor sockstat into stage_listening

- provision-haraka.sh
- provision-vpopmail.sh
- legacy mailfilter is at etc/mail/mailfilter (not etc/mailfilter)
- set redis server location for Haraka rate_limit plugin
> fix path for legacy mailfilter

- mail-toaster.sh
- provision-base.sh
- provision-host.sh
- provision-vpopmail.sh
- use TOASTER_ADMIN_EMAIL (defaults to postmaster@$TOASTER_EMAIL_DOMAIN) for admin email
> add TOASTER_ADMIN_EMAIL setting

- provision-dovecot.sh
- the vpopmail group is 'vchkpw', not 'vpopmail'
> fix vpopmail group to be vchkpw

- mail-toaster.sh
- provision-avg.sh
- provision-haraka.sh
- store tmp files in avg/spool (vs avg)
- use symlinks to store AVG signatures on data FS
Fixes #82
Checklist:
> preserve AVG signatures across deployments

- mail-toaster.sh
- provision-dovecot.sh
- provision-vpopmail.sh
The dovecot vpopmail option for the port now depends on the vpopmail package (vs the vchkpw binary).
- install vpopmail in dovecot jail (with same options as vpopmail in `vpopmail` jail)
Fixes #96 
Fixes #85
Checklist:
> install vpopmail in dovecot jail

- provision-haraka.sh
- provision-host.sh
- always create AVG mountpoint
- so users that have a haraka section in jail.conf with AVG and perform a reinstall and do not provision AVG the second time, do not have holes in their feet.
- add a couple missing entries to /etc/hosts
see #91
> always create AVG mountpoint

- .travis.yml
- provision-vpopmail.sh
- qmail/run.sh
- in tcp.smtp, use JAIL_NET_PREFIX instead of static 172.16.15 for net prefix
Fixes #107
> in tcp.smtp, use JAIL_NET_PREFIX

- mail-toaster.sh
- provision-base.sh
- provision-haproxy.sh
- provision-letsencrypt.sh
- provision-nginx.sh
- provision-php7.sh
- provision-rainloop.sh
- provision-roundcube.sh
- provision-sphinxsearch.sh
- provision-squirrelmail.sh
- provision-webmail.sh
- qmail/qqtool.pl
- adds support for [rainloop webmail](http://www.rainloop.net)
- move squirrelmail & roundcube out of webmail to their own jails
- adds SQUIRREL_SQL settings
- install a 2048 DH params file for haproxy
- fixed letsencrypt deployment script for dovecot
- haproxy rules need updating
- if squirrelmail had sqlite (default) storage, move data from webmail to squirrelmail data volume
- `mv /data/webmail/squirrelmail/* /data/squirrelmail/`
- if roundcube had sqlite storage, move data from webmail to roundcube data volume
Checklist:
> Rainloop webmail

- provision-dns.sh
- provision-host.sh
- unbound: move control files to /data
- host: skip patching jail rc on FreeBSD 11
Closes #155
> unbound: move control files to /data

- mail-toaster.sh
- provision-dns.sh
- provision-haproxy.sh
- provision-joomla.sh
- provision-letsencrypt.sh
- provision-memcached.sh
- provision-nginx.sh
- provision-nictool.sh
- provision-php7.sh
- provision-rainloop.sh
- provision-redis.sh
- provision-roundcube.sh
- provision-rsnapshot.sh
- provision-spamassassin.sh
- provision-squirrelmail.sh
- provision-tinydns.sh
- provision-webmail.sh
- if the provision script doesn't declare a JAIL_CONF_EXTRA, use default /data dir
- remove boilerplate from 16 scripts
> add default JAIL_CONF_EXTRA, reduced boilerplate

- mail-toaster.sh
- instead of stack \$path/data, use data_mountpoint() to show the correct path
Fixes # .
Checklist:
> in roadblock msg, show correct mount point

- mail-toaster.sh
convenient for jails with zfs data mounted from another zpool
> skip provisioning data fs if zfs mountpoint exists

- provision-rspamd.sh
- use redis for Lua [see here for details](https://github.com/vstakhov/rspamd/issues/766#issuecomment-240105002)
- Use for Storing BAYES tokens [from here](https://rspamd.com/doc/configuration/statistic.html)
Redis:
db=5 for Lua modules
db=6 for Bayes tokens
Fixes # .
Checklist:
> Update rspamd provision jail to make use of our Redis server

- provision-webmail.sh
- currently lighttpd logs 172.16.15.12 for every request
- instead, tell lighttpd to trust haproxy and log the X-Forwarded-IP header
> configure lighttpd to log real IP (trust haproxy)

- provision-nictool.sh
- change duplicate line 33 to install perl dependenciess for the client rather than the server twice
Checklist:
> fix duplicate line in provision-nictool.sh

- provision-host.sh
- qmail/run.sh
When building p5-HTTP-Daemon, make sure build succeeds before deinstall.
> assure successful build before deinstall

- include/php.sh
- provision-php7.sh
* when TOASTER_MYSQL, install `mysqli` and `pdo_mysql` only
* both are maintained
* drops `mysql` from PHP < 7 installs
* update php7 jail to use include/php.sh (DRY)
> php updates

- mail-toaster.sh
- provision-monitor.sh
- qmail/run.sh
- shorten ip6.addr installed message
- qmd: install with cpanminus (was CPANPLUS)
- add TOASTER_MUNIN setting
- only install nagios/munin in monitoring jail when enabled
Fixes #283 
Checklist:
> net mgmt: make use of NRPE/munin config settings

- mail-toaster.sh
- provision-base.sh
- provision-vpopmail.sh
- enable config for PUBLIC_IP4 and PUBLIC_IP6 (useful when public IPs are not bound to local NIC)
- show URL for FreeBSD package when downloading
- base: create dhparam.pem if missing (for upgrades)
- vpopmail: do not leave .bak file in periodic dir
Checklist:
> upgrading updates

- provision-rspamd.sh
Also, I added notes to the rspamd build page and the FAQ.
Fixes #302 
Checklist:
> rspamd: only enable phishing when RAM > 4GB

- provision-haraka.sh
- haraka: pre-download git repo (b/c npm got stoo-pede)
- haraka: manually install node-gyp, required but not longer included with node
- haraka: install ws & express in Haraka local (vs global) dir
- fixes #312
Checklist:
> haraka: pre-download git repo (b/c npm got stoo-pede)

- mail-toaster.sh
- provision-base.sh
- provision-elasticsearch.sh
- provision-geoip.sh
- provision-haproxy.sh
- provision-knot.sh
- provision-mediawiki.sh
- provision-monitor.sh
- provision-nictool.sh
- provision-nsd.sh
- provision-postfix.sh
- provision-smf.sh
- provision-squirrelcart.sh
- provision-wordpress.sh
- test/vmware.sh
- port rename vim-lite -> vim-console
- geoip: work around npm attempts to be clever
- mediawiki: working php7 install support
- smf: update smf version to 2.0.15
- squirrelcart: php 7.2 -> 7.1, for now
- squirrelcart: preserve store logo
- nsd: newly added build
- knot: preserve sys users & start sshd
- nictool: preserve system users
- elasticsearch: update where mem settings are set
- haproxy: install -devel with HTTP2 support, add "alpn h2,http/1.1" to each bind block to enable
> port rename vim-lite -> vim-console

- provision-haraka.sh
- provision-wordpress.sh
- haraka: store git co of Haraka to /root (vs /tmp)
- wordpress: disable logging for favicon.ico and robots.txt
> Haraka: store git co of Haraka to /root (vs /tmp)

- provision-spamassassin.sh
deprecated upstream: https://wiki.apache.org/spamassassin/SoughtRules
> spamassassin: disable sought rules

- provision-host.sh
- do test on /etc/ssl/private as well, instead of piggybacking on /etc/ssl/certs test
> create /etc/ssl/private when missing

- provision-base.sh
- provision-host.sh
- use ipinfo.io instead of freegeoip (deprecated)
- base: auto-update curl pkg when it has vulnerability
Fixes #364 
Checklist:
> use ipinfo.io instead of freegeoip (deprecated)

- provision-vpopmail.sh
- add proxy directives to lighttpd.conf
> vpopmail: get correct remote IP in lighttpd

- provision-squirrelmail.sh
- squirrelmail: use `/data/pref` for pref storage (same as migration docs, other uses)
> updating setting to be consistent

- provision-haraka.sh
- python not found during compilation
Fixes # .
```
ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3280000/sqlite3.c
/bin/sh: python: not found
```
See: https://gist.github.com/Infern1/fcf642570f85604ea274526e3d393665
Checklist:
> fix: python not found during compilation

- provision/base.sh
Avoids this error in nightly logs:
````
Warning: Variable $daily_status_security_pkgaudit_quiet is deprecated, use $security_status_pkgaudit_quiet instead.
````
> base: update renamed periodic.conf setting

- include/mysql.sh
- include/shell.sh
- mail-toaster.sh
- provision/base.sh
- provision/dspam.sh
- provision/gitlab.sh
- provision/horde.sh
- provision/joomla.sh
- provision/mediawiki.sh
- provision/monitor.sh
- provision/mysql.sh
- provision/nictool.sh
- provision/php7.sh
- provision/rainloop.sh
- provision/roundcube.sh
- provision/spamassassin.sh
- provision/squirrelmail.sh
- provision/vpopmail.sh
- test/get_jail_ip.sh
- test/vmware.sh
The FreeBSD mysql port now installs with an expired random password written to /root/.mysql_secret. In order to provision subsequent jails, a MySQL root password must be set. 
To manage this requirement, a mysql root password is generated and stored in mail-toaster.conf *and* in mysql/root/.my.cnf. Because of the obvious potential for security issues, the permissions of mail-toaster.conf are now automatically set to `600`. When the provision script connects to MySQL, if ~root/.mylogin.cnf or ~root/.my.cnf are configured, they are used. Otherwise, the password is passed on the command line.
- When the password is passed on the CLI, mysql emits a warning upon every connection. There are [workarounds](https://stackoverflow.com/questions/20751352/suppress-warning-messages-using-mysql-from-with …
> mysql provision with root password

- provision/base.sh
- provision/rspamd.sh
- rspamd: disable syslog until unbroken upstream
- base: add pkg & sudo to list of ports to autoupgrade
Fixes #432 
Checklist:
> Rspamd: disable syslog logging (broken upstream)

- include/nginx.sh
- provision/haproxy.sh
- haproxy->nginx: switch from x-forwarded-for header to proxy protocol
- support building against openssl 1.1.1 (adds TLS 1.3 support)
- if someone upgrades a jail with nginx in it (webmail), their new jail will expect the proxy protocol from haproxy. Haproxy.conf is not updated by default.
> haproxy/nginx: use proxy protocol (was x-forwarded-for)

- provision/rspamd.sh
rsmapd is binding to ipv6 but in haraka config rpamd is accessed by ipv4, this causes that haraka cannot use rpamd and is raising errors, and doesn't use rspamd in karma calculations. In the end we have mail server without proper spam scanning.
- change rspamd worker bind socket to ipv4
> change rspamd worker bind socket to ipv4

- provision/base.sh
- Change default vim theme
Fixes # 
Reading a `vimdiff`
> Change default theme to be more readable

- provision/clamav.sh
- provision/nsd.sh
- clamav-unofficial: update to 7.2.1
- nsd: start up sshd (for updates)
- nsd: if there's no nsd.conf in the data dir, symlink in the default one
> clamav-unofficial: update to 7.2.1

- provision/base.sh
- provision/dovecot.sh
This is required because dovecot has dropped the vpopmail AUTH option and so too has the FreeBSD port of dovecot.
YMMV. It's working for me.
> dovecot: passdb/userdb switch from vpopmail -> sql

- provision/wordpress.sh
cannot create outside it as the path does not exist
> wp: create link within stage jail

- provision/roundcube.sh
Apparently this had never been tested, we're on BSD `sed`, but even with GNU sed the regexes were wrong.
- Fix `sed` regexes in Roundcube php.ini customization script.
> Fixed roundcube php.ini customizations

- include/php.sh
- Some unrelated commit changed `find ... -print` to `find ... -print0`, ignoring `xargs` in the pipe. Add `-0` to `xargs`. Otherwise timezone is always set to America/LA
> Fix timezone detection

- mail-toaster.sh
E.g. `add_jail_conf gitlab` won't work when `jail.conf` contains a `gitlab_runner` entry.
> Fix jail.conf updating for common-prefixed jail names

- provision/unifi.sh
- and disable mongod install/test, b/c unifi bundles its own
> unifi: preinstall snappyjava (dep)

- mail-toaster.sh
- provision/puppeteer.sh
- install requires PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
- also install google-charts-node
- used by beadedstream/db#392
> Puppeteer: new jail

- provision/dovecot.sh
Fix error semaphore
- allow sysv to run empty
- change commands to empty so error regex compilation failed goes away
Fixes # .
`regex compilation failed`
Checklist:
> Fix error Regex compilation failed

- include/mysql.sh
-  Specify CHARACTER SET utf8mb4 COLLATE utf8mb4_bin in MySQL CREATE DATABASE invocations. All kinds of mess happen otherwise.
Checklist:
> Create MySQL databases in proper encoding

- include/php.sh
For some timezones, timezone detection in configure_php_ini() is broken, e.g. here this code returns multiple timezone names for a single MD5 hash:
```
(TZ=$(md5 -q /etc/localtime); find /usr/share/zoneinfo -type f -print0 | xargs -0 md5 -r | grep "$TZ" )
4790e83465681cefbf852aed265354bf /usr/share/zoneinfo/Europe/Berlin
4790e83465681cefbf852aed265354bf /usr/share/zoneinfo/Europe/Copenhagen
4790e83465681cefbf852aed265354bf /usr/share/zoneinfo/Europe/Oslo
4790e83465681cefbf852aed265354bf /usr/share/zoneinfo/Europe/Stockholm
4790e83465681cefbf852aed265354bf /usr/share/zoneinfo/Arctic/Longyearbyen
4790e83465681cefbf852aed265354bf /usr/share/zoneinfo/Atlantic/Jan_Mayen
```
The patch skips all entries except the first one.
-
-
-
Fixes # .
Checklist:
> Fix timezone detection for php.ini

- mail-toaster.sh
When JAIL_ORDERED_LIST contains a jail name which is a substring of another jail name, the former can't be enabled.
-  Use whole word comparison in enable_jail().
> Fix check if jail is already enabled in enable_jail

- mail-toaster.sh
- When TOASTER_USE_TMPFS=1 (the default is 0), mount tmpfs on /tmp and /var/run in jails.
Checklist:
> Added an option, TOASTER_USE_TMPFS=1, to use tmpfs for /tmp and /var/run in jails

- provision/rspamd.sh
- When TOASTER_USE_TMPFS is defined, rspamd can't find expected /var/run/rspamd directory, so we need to recreate it on jail start. In my installation, it's the only app which needed this workaround, but my setup is far from standard, e.g. I don't run haproxy and haraka.
> rspamd needs to recreate /var/run/rspamd when /var/run is ephemeral

- mail-toaster.sh
- provision/base.sh
- provision/dhcp.sh
- provision/dns.sh
- provision/dspam.sh
- provision/elasticsearch.sh
- provision/haraka.sh
- provision/horde.sh
- provision/host.sh
- provision/mailtest.sh
- provision/mongodb.sh
- provision/prometheus.sh
- provision/rspamd.sh
- provision/spamassassin.sh
- provision/wildduck.sh
- provision/zonemta.sh
- host: avoid showing "error" when loading pf.ko
- host: update pf rule so IPv6 NAT works
- dns/mailtest: allow raw sockets in jails
- mt: use /etc/jail.conf.d if exists
- mt: remove jail.conf.d during unprovision
- base: add check for host setup
- mt: smarter JAIL_CONF_EXTRA handling, if $ZFS_DATA_MNT is not found, then add it
- dspam: update for mysql 8
- zonemta: added
- wildduck: added, webmail
Checklist:
> host: avoid showing "error" when loading pf.ko

- mail-toaster.sh
- provision/dhcp.sh
- provision/dovecot.sh
- provision/haproxy.sh
- provision/haraka.sh
- provision/host.sh
- mt: tighten up detection of data fs mount
- mt.stop_jail: if jail isn't running, don't attempt to stop it
- mt.store_config(), new function.
- dhcp,dovecot,haraka,haproxy: PF port mappings moved to jails config
Previously, PF rules for port 80 & 443 were in /etc/pf.conf and pointed to haproxy. After this PR, those same PF redirect rules are located at `$data/haproxy/etc/pf.conf.d/rdr.conf`. Same goes for MUA, MSA, and MTA ports which moved to `$data/dovecot/etc/pf.conf.d/rdr.conf` and similarly haraka and dhcp.
- encapsulation: keep all the jail needs contained within its jail.conf and data partition.
- flexibility: as an example, one could replace haproxy with nginx, haraka with postfix/opensmtpd/other, etc.
- upon boot, some PF rules may not be ready due to dependencies.
- …
> PF anchors - load PF rules as jails start/stop

- provision/letsencrypt.sh
Haraka has two ways to configure TLS: drop two specially named files the config directory (always done, for the "default" TLS cert which is served when SNI is not present), and put a bunch of PEM files into `config/tls`. When using the latter, also keep the default TLS file updated.
> LE: haraka provision also update default TLS

- .gitignore
- contrib/exorcise_maildrop.sh
- include/vpopmail.sh
- mail-toaster.sh
- provision/base.sh
- provision/clamav.sh
- provision/dns.sh
- provision/dovecot.sh
- provision/dspam.sh
- provision/geoip.sh
- provision/ghost.sh
- provision/haproxy.sh
- provision/haraka.sh
- provision/horde.sh
- provision/host.sh
- provision/mysql.sh
- provision/postfix.sh
- provision/roundcube.sh
- provision/snappymail.sh
- provision/spamassassin.sh
- provision/squirrelmail.sh
- provision/sqwebmail.sh
- provision/unifi.sh
- provision/vpopmail.sh
- provision/whmcs.sh
- qmail/run.sh
- to be more consistent with how other jails works
- to store persistent /data/etc and /data/log directories
- fix: overly broad sed scripts on clamd.conf
- rework filesystem mounts
- goals: simplify, make more explicit, make more flexible
- instead of `mount +=` lines in jail.conf, a single `mount.fstab=$data/etc/fstab` setting
- previously: information about "special" fstab mounts was embedded in functions in mail-toaster.sh and in the provision scripts.
- now: a custom `$data/etc/fstab` file is generated for each jail. The data fs is mounted automatically, any extra filesystems must be added as fstab entries within the provision script as JAIL_FSTAB.
- for staging, a sed script rewrites `$data/etc/fstab` to `$data/etc/fstab.stage`
> always mount data dir at /data, new data/etc/fstab

- provision/dns.sh
- provision/webmail.sh
- all 3 are effectively unmaintained. Don't encourage their use, but keep it easy to manually enable them.
> webmail: disable squirrelmail, rainloop, and sqwebmail

- provision/host.sh
- test/vmware.sh
Instead of editing /etc/ssh/sshd_config, override the config file by setting sshd_flags in /etc/rc.conf.
> host: move sshd config tweaks to rc.conf

- provision/host.sh
- host: when local/etc/rc.d or local/bin don't exist, create them
- host: if no public IPv6 detected, remove empty entry from ext_ip table
Fixes #589
> host: vivify local dirs, improve pf when no ipv6

- contrib/pfrule.sh
- include/shell.sh
- mail-toaster.sh
- provision/base.sh
- provision/dcc.sh
- provision/dovecot.sh
- provision/haproxy.sh
- provision/haraka.sh
- provision/host.sh
- provision/webmail.sh
- provision/wildduck.sh
- test/run.sh
- mt: default NTPd is now openntpd
- mt: install pfrule from GH repo (vs inline)
- add mt6-fetch, get_jail_data
- pfrule.sh:
- adds a -n option
- adds binat loading support
- loads tables in pf.conf.d
- unload is smarter now
- host: ntpd stop -> onestop
- base: fix jail config so `service jail start base` works
Fixes #600 
Checklist:
> mt: update pfrule.sh, improve table handling

- mail-toaster.sh
- provision/dcc.sh
- provision/dns.sh
- provision/host.sh
- provision/vpopmail.sh
- provision/webmail.sh
- vpopmail: improve lighttpd config
- host: in pf rule, declare IPv6 network (instead of `(lo1)` syntax)
- host: add ipv6 settings
- mt: only ipv6 in jails when host has public IPv6
- mt: consolidate all jail settings into host block
Fixes #610 
Checklist:
> host: jail ipv6 nat

- provision/clamav.sh
- provision/dns.sh
- provision/host.sh
- dns: set rc to use /data/unbound.conf if exists
> clamav: fall back to port build if pkg install fails
