msimerson/Mail-Toaster-6

- .gitignore
- .travis.yml
- configure-host.sh
- mail-toaster.sh
- provision-avg.sh
- provision-base.sh
- provision-clamav.sh
- provision-dns.sh
- provision-dovecot.sh
- provision-geoip.sh
- provision-haproxy.sh
- provision-haraka.sh
- provision-mysql.sh
- provision-redis.sh
- provision-rspamd.sh
- provision-spamassassin.sh
- provision-vpopmail.sh
- provision-webmail.sh
- test instructions
* added shellcheck
* many lint updates
> add .travis.yml

- mail-toaster.sh
- mt6-mailfilter.txt
- provision-avg.sh
- provision-base.sh
- provision-dovecot.sh
- provision-dspam.sh
- provision-haraka.sh
- provision-monitor.sh
- provision-mysql.sh
- provision-rspamd.sh
- provision-vpopmail.sh
- provision-webmail.sh
* provision now mirrors script and then execs
* automount aux data partitions in staging
* check before (re)mounting a data fs
* added WEBMAIL_HTTPD check for webmail httpd daemon choice
* add provision-dspam and provision.monitor
> dspam & monitor basics

- mail-toaster.sh
- provision-avg.sh
- provision-dovecot.sh
- provision-haraka.sh
- provision-spamassassin.sh
* avg status messages
* limit PUBLIC_IP[4|6] to first IP
* always use 'stage' as name for staging jail
* now $1 in start_staged_jail can be useful name
* haraka: enable redis plugin
> (un)mount aux data fs while building jails with them

- mail-toaster.sh
- provision-base.sh
- provision-dns.sh
- provision-haproxy.sh
- provision-haraka.sh
- provision-host.sh
- provision-rspamd.sh
- provision-spamassassin.sh
- provision-vpopmail.sh
- provision-webmail.sh
* add get_reverse_ip()
* use get_jail_ip everywhere (vs $JAIL_NET_PREFIX.N)
* only set up squirrelmail_mysql when TOASTER_MYSQL=1
> consistent use of get_jail_ip

- mail-toaster.sh
- provision-base.sh
- provision-host.sh
* instead of static 4th octets, make them start at a configurable octet
(default: 1) and increment up.
* host: check for existing settings before applying updates
* ws: spaces -> tabs
> calc 4th IP octet based on start

- ROADMAP.md
- provision-clamav.sh
- provision-haraka.sh
- provision-spamassassin.sh
- provision-vpopmail.sh
* install nrpe agents in spamassassin, clamav, vpopmail
* haraka: 
* replace `max_unrecognized_commands` plugin with `limits`
* configure geoip plugin's *report_as*
> install nrpe agents when asked for

- .travis.yml
- Dockerfile
- README.md
- mail-toaster.sh
- provision-base.sh
- provision-host.sh
* add travis & codeclimate badges
* remove dspam from ordered list
* unprovision is more thorough now
> add travis badge

- README.md
- mail-toaster.sh
- provision-dns.sh
- provision-nginx.sh
this is #29, rebased and squashed.
closes #29
> attempt at provision-nginx.sh

- provision-base.sh
> remove sudo from base

- provision-webmail.sh
> raise nginx upload size limit

- mail-toaster.sh
- provision-base.sh
- provision-dns.sh
- provision-haproxy.sh
- provision-host.sh
- provision-joomla.sh
- provision-vpopmail.sh
- provision-webmail.sh
* base will have decendents, so must be updated
* vpopmail: install legacy mailfilter (for mt5 upgrades)
* webmail: create /data/htdocs, for user configurable index page(s)
* haproxy: get TLS certs via directory declaration
* joomla: new build script
> permit updating base jail (vs destroy/rebuild)

- provision-clamav.sh
- provision-spamassassin.sh
- provision-vpopmail.sh
* in case someone *wants* it installed but forgot to export TOASTER_NRPE
> emit messages when skipping nrpe plugins

- provision-haraka.sh
so karma.ini changes are preserved when updating
> use correct file test for karma.ini

- provision-minecraft.sh
now it saves both etc/minecraft-server and var/db/minecraft-server in the data volume.
> store /var/db/minecraft-server as persistent

- mail-toaster.sh
- provision-haraka.sh
- install haraka config dir to a data volume (/data/haraka)
- install modern-syslog from git (until npm release is made)
Fixes #51 
Fixes #49 
Checklist:
> add a persistent haraka data dir

- mail-toaster.sh
- provision-dns.sh
- provision-memcached.sh
- provision-sphinxsearch.sh
- Memcached provision
-
-
Fixes # .
Checklist:
> Memcached provision

- mail-toaster.sh
- when creating mail-toaster.conf, prompt for hostname values
- removes need to edit new
Checklist:
> prompt for required values

- mail-toaster.sh
- provision-host.sh
- when updating jail.conf, emit status message
> when updating jail.conf, emit status message

- mail-toaster.sh
- provision-haraka.sh
> feature: run pkg audit -F when promoting

- .travis.yml
- mail-toaster.sh
- provision-dns.sh
- provision-elasticsearch.sh
- provision-host.sh
* adds build & deploy support for [elasticsearch](http://elastic.co)
* install shellcheck via apt whitelist (faster)
> Elasticsearch

- mail-toaster.sh
- provision-base.sh
- provision-dovecot.sh
- provision-spamassassin.sh
- create a dovecot data dir
- preserve existing dovecot config files (when present)
Checklist:
> store local/etc/dovecot in /data

- provision-base.sh
- provision-haproxy.sh
- provision-haraka.sh
- haproxy: more precise name for websocket server
- haraka: add haproxy setup
- base: disable periodic mount checks inside jails
> Haraka haproxy

- provision-base.sh
* it causes empty periodic emails to be sent
> disable security_inline

- mail-toaster.sh
- provision-nictool.sh
> adding nictool support

- provision-haproxy.sh
- provision-haraka.sh
- enable haraka-plugin-log-reader
- update haproxy route for /logs
- update haproxy route for sqwebmail
- configure haraka helo.checks plugin
> enable haraka-plugin-log-reader

- mail-toaster.sh
- provision-spamassassin.sh
- add data FS for spamassassin
- store spamassassin etc & var/db directories on DATA fs
- configure & register razor-agents
- skip installing sought rules when already installed
Fixes #83
Checklist:
> spamassassin data fs

- provision-vpopmail.sh
- permit vpopmail provision to succeed even when mysql connections fail
- such as when mysql has a root password and CLI login options not set
> permit vpopmail deploy after mysql connect failure

- provision-haraka.sh
- install haraka plugins locally (data fs)
> Haraka local plugin

- provision-clamav.sh
> update clamav unofficial to 5.4.1

- provision-mysql.sh
* disable innodb double writes
> disable innodb double writes (redundant on ZFS)

- provision-dovecot.sh
- provision-haraka.sh
- provision-sqwebmail.sh
- provision-vpopmail.sh
- qmail/qqtool.pl
- qmail/toaster-quota-report
Changes
- install and enable toaster-quota-report
- qqtool: fix path to qmail-smtpd service dir
- haraka: remove spurious line
- correct url to mail filter
- sqwebmail: improve vpopmail build support
TODO
> install and enable toaster-quota-report

- provision-mysql.sh
- create mysql db dir, before attempting to write default my.cnf
> create mysql db dir

- mail-toaster.sh
- provision-base.sh
- provision-clamav.sh
- provision-dns.sh
- provision-dovecot.sh
- provision-dspam.sh
- provision-geoip.sh
- provision-haproxy.sh
- provision-host.sh
- provision-joomla.sh
- provision-memcached.sh
- provision-minecraft.sh
- provision-monitor.sh
- provision-mysql.sh
- provision-nginx.sh
- provision-nictool.sh
- provision-php7.sh
- provision-redis.sh
- provision-rspamd.sh
- provision-spamassassin.sh
- provision-sphinxsearch.sh
- provision-sqwebmail.sh
- provision-vpopmail.sh
- provision-webmail.sh
- declare jail_*_extra in every jail
- to prevent inadvertant inclusion of extras from other jails
> declare jail_*_extra in every jail

- mail-toaster.sh
- provision-spamassassin.sh
- remove UPDATE_AND_COMPILE pkg opt
- add p5-Net-CIDR-Lite p5-IO-Socket-INET6 optional deps
Fixes #119
> remove UPDATE_AND_COMPILE pkg opt

- provision-haraka.sh
- enable haraka.log rotation
Fixes #106
> enable haraka.log rotation

- mail-toaster.sh
- provision-dns.sh
- provision-host.sh
- rename JAIL_ORDERED_LIST -> JAIL_STARTUP_LIST
- JAIL_ORDERED_LIST is now the complete list of jails
- replace 3x jail lists with for iterator
> replace 3x jail lists with for iterator

- mail-toaster.sh
- remove has_data_fs
- always create the data FS for each jail
Related to #128
> provide a data FS for every jail

- .travis.yml
- mail-toaster.sh
- test/get_jail_ip.sh
- and add test coverage for get_jail_ip
> prevent previous ENV from causing incorrect IP enumeration

- provision-host.sh
- install /etc/periodic.conf to the host
> host: install /etc/periodic.conf

- mail-toaster.sh
- provision-tinydns.sh
> add tinydns support

- provision-dns.sh
> add test for unbound running

- provision-letsencrypt.sh
> add letsencrypt support

- provision-haproxy.sh
- provision-haraka.sh
- provision-rainloop.sh
- fix dhparam file creation
- rainloop: chown the data volume
- haproxy: move options into correct section
> fix dhparam file creation

- mail-toaster.sh
- provision-dns.sh
- provision-joomla.sh
- use the unbound data fs
- unprovision improvements
- joomla: update to php7
Fixes #128
> Unbound data fs

- provision-elasticsearch.sh
- if two ES instances access the same data dir, bad things can happen
- so start up ES with default data (/var/db) and after testing, switch to /data/var
> es: do not switch data to /data until after test

- provision-base.sh
- provision-host.sh
- provision-rainloop.sh
- provision-roundcube.sh
- qmail/qqtool.pl
- rainloop: create config dir for domains/default.ini file
- roundcube: update URL path for installer
- bourne: move aliases to system-wide profile
- qqtool: correct path to qmail-send supervise dir
- base: don't make changes to host shell inside base script (avoid side effects)
> Roundcube sql fix

- mail-toaster.sh
- provision-host.sh
- provision-letsencrypt.sh
- provision-rsnapshot.sh
- provision-spamassassin.sh
- check that every jails data fs is declared in /etc/jail.conf
- letsencrypt: skip provision when data/$jail missing
- host: use geoip query to set SSL cert default location
- host: upgrade improvements
> Upgrade data fs check

- provision-base.sh
- provision-host.sh
- provision-nictool.sh
- provision-tinydns.sh
- base: better alias detection
- host: install ca_root_nss if not already
- nictool: install tools for exporting
- tinydns improvements: ipv6, tests
> tinydns install improvements & small fixes

- include/nginx.sh
- include/php.sh
- provision-dns.sh
- provision-haproxy.sh
- provision-host.sh
- provision-joomla.sh
- provision-mediawiki.sh
- provision-rainloop.sh
- provision-roundcube.sh
- provision-rspamd.sh
- provision-squirrelmail.sh
- provision-vpopmail.sh
- provision-webmail.sh
- create `includes/php.sh` & `includes/nginx.sh`
- update PHP & nginx installing jail recipes to use include
- sed syntax cleanups
- add haproxy config for mediawiki
> reduce redundant PHP & nginx code

- include/nginx.sh
- provision-mediawiki.sh
- provision-rainloop.sh
- provision-roundcube.sh
- provision-smf.sh
- provision-squirrelmail.sh
- provision-webmail.sh
and made each script that uses includes/nginx shorter and simpler
> moved boilerplate to nginx.conf

- include/nginx.sh
- include/php.sh
- provision-haproxy.sh
- provision-haraka.sh
- provision-host.sh
- provision-mysql.sh
- provision-smf.sh
- provision-wordpress.sh
- smf: store custom avatars on /data
- haraka: fix path for newsyslog
- nginx: move proxy out of server {}
- wordpress: added build support
- add unix socket support for PHP
Fixes # .
Checklist:
> smf: store custom avatars on /data

- include/shell.sh
- provision-base.sh
- provision-haraka.sh
- provision-host.sh
* to get reused by host & base steps
* haraka: rename config_ -> configure_, to be consistent
> shell: move install/config into include/shell

- provision-spamassassin.sh
> only add 127 to spamd args once

- include/vpopmail.sh
b/c doing it the other way lets the pkg installer clobber the symlinks
fixes #195
> install qmail first, then set up symlinks

- provision-haproxy.sh
- provision-letsencrypt.sh
> after successful LE cert install, update haproxy ssl crt dir

- provision-haraka.sh
> install but skip enabling limit plugin

- mail-toaster.sh
- provision-haproxy.sh
- provision-horde.sh
Mail and Ingo (mailfilter for Maildrop)
- Make Horde available, main use is, ingo for maildrop filters
Checklist:
> Provision Horde Groupware,

- mail-toaster.sh
- provision-mysql.sh
- Fix location of my.cnf
- Fix type sphinxsearch in jail list
-
-
-
Fixes # .
Checklist:
> Fix for sphinxsearch type and mysql my.cnf

- include/php.sh
- see here #215 
-
-
Fixes # .
Checklist:
> Set php timezone auto

- include/nginx.sh
- mail-toaster.sh
- provision-dovecot.sh
- provision-haproxy.sh
- provision-haraka.sh
- provision-minecraft.sh
- provision-mongodb.sh
- provision-spamassassin.sh
- provision-sphinxsearch.sh
- provision-squirrelcart.sh
- provision-sqwebmail.sh
- provision-tinydns.sh
- provision-unifi.sh
- provision-vpopmail.sh
- provision-whmcs.sh
- replace a dozen+ "make -C ..." with stage_port_install
> add stage_port_install

- mail-toaster.sh
- provision-host.sh
- provision-letsencrypt.sh
- provision-roundcube.sh
- provision-sqwebmail.sh
- provision-whmcs.sh
- add jails to startup list when created
- whmcs: add hash to PHP module list (for updates)
- sqwebmail: install GPG package (to avoid building it from source)
- letsencrypt: fail smarter when TLS issue fails
- roundcube: remove exta $ char that cause failure when preserving config across installs
> batch-o-updates

- provision-elasticsearch.sh
- provision-haproxy.sh
- provision-haraka.sh
- provision-letsencrypt.sh
- provision-squirrelcart.sh
> provision Elasticsearch 5 (was 2)

- .gitlab-ci.yml
> add stub gitlab config

- .gitlab-ci.yml
- .travis.yml
- include/php.sh
- include/shell.sh
- mail-toaster.sh
- provision-avg.sh
- provision-base.sh
- provision-dns.sh
- provision-dovecot.sh
- provision-gitlab-runner.sh
- provision-gitlab.sh
- provision-haraka.sh
- provision-host.sh
- provision-monitor.sh
- provision-squirrelcart.sh
- provision-sqwebmail.sh
- provision-vpopmail.sh
- provision-webmail.sh
- test/vmware.sh
- adds GitLab CI testing
- using gitlab-runners + ssh executor
- to a remote FreeBSD server (I run inside vmware)
- I use [gitlab.com](https://gitlab.com) (no maintenance) but this includes setup for local GitLab
- I install gitlab runners on my workstation (Mac OS X)
- alternatively, this includes a gitlab runner jail for FreeBSD
- switch pkg from quarterly -> latest
Checklist:
> CI testing via GitLab

- provision-host.sh
There are plenty of ssh bruteforce blockers. denyhosts. fail2ban. [sentry](https://github.com/msimerson/sentry). I think sshguard is better for a couple reasons:
1. no interpreter (perl/python/etc) required
2. syslog & daemon support
I think we should have one installed by default. If there are similarly great alternatives, consider offering an alternative.
> install sshguard w/pf config

- Changes.md
- provision-haraka.sh
- provision-letsencrypt.sh
- haraka: skip installing Haraka dev deps with `npm i --production`
- letsencrypt: install socat
> npm --production

- provision-haraka.sh
- update path to haraka-plugin-p0f's rc.d file
- update Haraka locally installed plugin list
> haraka p0f

- provision-haproxy.sh
- provision-haraka.sh
> haraka: add p0f config, haproxy: add gzip opts

- provision-dovecot.sh
- provision-monitor.sh
Conserve existing munin data files
Conserve existing munin.conf
Update to use CGI method for lighttpd (reduce load)
Compile pigeonhole to be not out of sync with dovect
-
-
-
Fixes # .
Checklist:
> Update monitor jail + fix for dovecot pigeonhole

- mail-toaster.sh
- provision-dspam.sh
- provision-horde.sh
- provision-host.sh
- provision-joomla.sh
- provision-mediawiki.sh
- provision-mysql.sh
- provision-nictool.sh
- provision-roundcube.sh
- provision-wordpress.sh
- have mysql default to disabled
- when not defined, have SQUIRREL_SQL inherit TOASTER_MYSQL
Fixes #262
Checklist:
> mysql default off

- mail-toaster.sh
identified in email by Graham (thanks!)
> correct test for jail id result

- provision-dovecot.sh
- reduce output of curl by using -s, add the -S to see errors
- Fixes #292 .
> Curl not installed and logging of curl reduction

- include/vpopmail.sh
- provision-dns.sh
- provision-haraka.sh
- qmail: add comment when updating control/me
- dns: configure private DNS for TOASTER_HOSTNAME
- haraka: if config/me does not exist, write TOASTER_HOSTNAME to it
Fixes #282
> qmail control/me, haraka/config/me

- provision-dns.sh
- dns: extend SPF policy to local nets
- add MX record, since TXT record overrides public DNS record for the MX
> dns: extend SPF policy to local nets

- provision-mysql.sh
> generate TLS certs needed for sha256 password

- provision-dspam.sh
- provision-horde.sh
- provision-letsencrypt.sh
- provision-nictool.sh
- provision-roundcube.sh
- provision-spamassassin.sh
- provision-squirrelmail.sh
- add IPv6 mysql grants for dspam, horde, nictool, roundcube, spamassassin, and squirrelmail
- add letsencrypt deployment script for mysql
Fixes #257
> mysql ipv6 grants

- provision-horde.sh
- provision-letsencrypt.sh
- provision-roundcube.sh
- add left indent
- le: mv rm into conditional where used
- roundcube: update match rule for smtp_server URL
Checklist:
> small minor updates

- provision-geoip.sh
> geoip: restrict to npm 4 since 5 is unstable

- provision-dovecot.sh
- provision-geoip.sh
- provision-haproxy.sh
- provision-haraka.sh
- provision-roundcube.sh
- provision-tinydns.sh
- geoip: install npm3 (and node 6) to get node LTS (not version sensitive, just avoiding node 9 because it's a -devel branch)
- haproxy: fix conditional that chooses libressl option
- haraka: install python meta port
- roundcube: fix sed command for updating config val smtp_server
- tinydns: test with TOASTER_HOSTNAME if example.com not in data file
- dovecot: if sieve not in local.conf, do not try compiling sieve
- haraka: skip LMTP delivery until Haraka outbound is fixed
- geoip,haraka: install using npm-node8
> batch o' updates

- provision-base.sh
- provision-haraka.sh
> haraka: enable newsyslog (log rotation)

- include/nginx.sh
- provision-letsencrypt.sh
> letsencrypt: update htdocs dir to match nginx config

- mail-toaster.sh
- provision-dns.sh
- provision-haraka.sh
- mt.sh: remove not-always-valid message
- haraka: only create dcc.ini once
- dns: no duplicate TXT when HOSTNAME=MAIL_DOMAIN
> DNS same hostname

- provision-horde.sh
- provision-monitor.sh
- provision-rainloop.sh
- provision-roundcube.sh
- provision-wordpress.sh
- horde: remove unused copy/paste
- monitor: install npre3 (was nrpe2-ssl)
- updates for PHP 7.2 install: rainloop, roundcube, wordpress
> Nrpe3 and PHP 7.2 updates

- provision-dovecot.sh
- provision-haraka.sh
- Fixes error in log
```
[ERROR] [-] [helo.checks] deprecated setting mismatch renamed to host_mismatch 
```
-
-
Fixes # .
Checklist:
> Helo checks error in logging

- mail-toaster.sh
- provision-haproxy.sh
- provision-prometheus.sh
work in progress for [prometheus](https://github.com/prometheus/prometheus)
> WIP: prometheus build support

- provision-dovecot.sh
- provision-haraka.sh
> Make sure Bash is installed

- include/vpopmail.sh
- provision-postfix.sh
- vpopmail: add vpopmail settings when missing
- postfix: preserve /etc/aliases
Fixes #324
> 324 vpopmail make conf

- provision-grafana.sh
> install just grafana

- .travis.yml
- provision-grafana.sh
- provision-squirrelcart.sh
> update grafana to install v5

- .travis.yml
> shellcheck: disable 2038 in include/*.sh

- provision-haraka.sh
> haraka: fix sed match to enable newsyslog

- provision-dovecot.sh
> dovecot: update config for 2.3

- provision-roundcube.sh
> roundcube: enable managesieve plugin

- provision-roundcube.sh
- provision-squirrelmail.sh
> update roundcube & squirrelmail due to -phpVV rename

- provision-dhcp.sh
- provision-grafana.sh
- provision-spamassassin.sh
- provision-vpopmail.sh
- dhcp: update to version 4.4
- grafana: fix typo mdkir
- perl ports build fix
Fixes # .
Checklist:
> Misc build fixes

- provision-mysql.sh
- Upgrade to 10.3
https://mariadb.com/kb/en/library/mariadb-1039-release-notes/
Fixes # .
- Security warning from pkg audit with 10.2
Checklist:
> Upgrade to current stable of MariaDB 10.3

- provision-rspamd.sh
- was rspamd.conf
- set rspamd logging level to notice
fixes #319
> store redis settings in redis.conf

- include/nginx.sh
- provision-haproxy.sh
- provision-roundcube.sh
- haproxy: remove -devel (1.8 is "stable" now and 1.9 has ouch BUGS!)
- roundcube: update path to nginx mime.types file
- nginx: enable gzip compression
Fixes # .
Checklist:
> Haproxy no devel

- provision-elasticsearch.sh
- provision-host.sh
- provision-nsd.sh
- provision-rsnapshot.sh
> host: check that timezone is set

- provision-clamav.sh
- provision-haproxy.sh
- provision-rainloop.sh
- provision-roundcube.sh
- provision-webmail.sh
- clamav: update unofficial 5.4.1 -> 5.6.2
- haproxy: add grafana support
- roundcube: apply customizations to php.ini (needs testing)
- webmail: show/hide services based on availability
Fixes #261
Checklist:
> Index checks options

- provision-haraka.sh
* update plugin names of geoip, p0f, qmail-deliverable
* enable haraka-log-reader
fixes #380
fixes #379
Checklist:
> update plugin names of geoip, p0f, qmail-deliv

- provision-influxdb.sh
> Give Influx some more time to start

- provision-elasticsearch.sh
- provision-haraka.sh
- haraka: install node 10 (was 8)
- haraka: only enable AVG if the jail is running
- elastic: make upgrading smoother
Checklist:
> Haraka & Elastic updates

- provision-clamav.sh
- provision-dcc.sh
- provision-haraka.sh
- provision-mysql.sh
- provision-spamassassin.sh
- clamav: update unofficial version 5.6.2 -> 6.1.0
- mysql: install when any _MYSQL option enabled
- elastic: make upgrading smoother
- spamassassin: remove dcc package install (no longer built)
- dcc: port install (was pkg), path to dcc_conf
- haraka: only enable AVG plugin if the jail is running
Checklist:
> misc build updates

- .gitlab-ci.yml
- test/vmware.sh
> gitlab: update config for provision/* names

- include/php.sh
- mail-toaster.sh
- provision/borg.sh
- provision/haproxy.sh
- provision/nagios.sh
- add nagios provision
- add borg provision
> add nagios & borg provision scripts

- provision/postfix.sh
- improvements in default DKIM support
> postfix: add default config for dkim

- mail-toaster.sh
> add MT version check

- mail-toaster.sh
> mt: when enabled, add automount config for ports and/or pkg cache

- mail-toaster.sh
- provision/mysql.sh
- provision/nictool.sh
- provision/whmcs.sh
- raise mt6-update to keep in scope
- mysql: quote the password, JIC
- whmcs: create basic location config if missing
> raise mt6-update to keep in scope

- include/vpopmail.sh
- provision/mysql.sh
- Upgrade MariaDB to 10.4
Fixes # 
- Security warnings
> Mariadb upgrade to 10.4

- provision/mysql.sh
> mysql: remove extra quotes

- provision/geoip.sh
- geoip: prompt for license key
- geoip: add support for geoipupdate
> geoip: prompt for license key

- provision/wordpress.sh
> wp: add php-json module

- provision/haproxy.sh
- provision/squirrelmail.sh
fixes #448 
note: not build tested. ENOTIME error.
> haproxy: replace deprecated reqirep with http-request

- mail-toaster.sh
- provision/base.sh
- provision/host.sh
- provision/roundcube.sh
- test/vmware.sh
- roundcube: curl needs to send db init request with proxy protocol
- base: add libxml2 to auto-security-update packages
- base: disable 'pkg audit' (it creates lots of emails)
- host: enable pkg audit in jails (reports audit issues in all jails in one email)
- vmware: update version to 12.1p2
- base: auto-upgrades, move list into variable
> roundcube proxy

- mail-toaster.sh
- provision/host.sh
- provision/mongodb.sh
- mongo: check & set vm.max_wired if needed
- consistent use of _j
> mongo: check & set vm.max_wired if needed

- provision/dns.sh
- add local-zone declaration
Fixes #458 
Checklist:
> dns: add local-zone: typetransparent declaration

- provision/clamav.sh
- provision/haraka.sh
- provision/nsd.sh
- provision/whmcs.sh
- whmcs: fix typo, update PHP to 7.4
- clamav: update unofficial to 7.2
- nsd: install default nsd.conf when staging
- haraka: update node 10 -> 12
Checklist:
> build updates: whmcs, clamav, nsd, haraka

- provision/vpopmail.sh
- vpopmail: fix ipv6 config for lighttpd
- vpopmail: set state dir for lighttpd config
> vpopmail: ipv6 addr for lighttpd, lighttpd state dir

- include/php.sh
> Fix php_fpm restart to run in staged jail

- provision/dovecot.sh
> dovecot: improve grep regex that detects SQL conversion

- Changes.md
- provision/base.sh
- provision/unifi.sh
- test/vmware.sh
- rename vim-console -> vim
- unifi: install v5 -> v6
- update Changes.md
> vim: port vim-console renamed -> vim

- provision/dovecot.sh
- provision/mongodb.sh
- dovecot: configure SQL auth on new installs
- mongodb: add data mount to jail.conf
- mongo: bump version to 4.4
Checklist:
> dovecot: configure SQL on new install

- mail-toaster.sh
- provision/certbot.sh
- provision/dovecot.sh
so auth tests work. fixes #496
> dovecot: update staged jail resolve.conf earlier

- provision/dovecot.sh
- provision/vpopmail.sh
- provision/wildduck.sh
to avoid this error: Error: Namespace "": Mail storage autodetection failed with home...
- add some config options for vqadmin (not enabled)
- add wildduck installer (beta)
> dovecot: add mail_location setting to namespace

- provision/vpopmail.sh
make it working on provision
Fixes # . #487
> Fix build Fbsd13

- provision/rainloop.sh
> rainloop: update for port rename

- provision/mysql.sh
- Added a missing `local` declaration
- Multiple typos fixed
> Cosmetic/typo fixes in provision/mysql.sh

- provision/haproxy.sh
- provision/haraka.sh
- provision/knot.sh
- provision/mysql.sh
- test/vmware.sh
- haproxy: remove nbproc (removed in 2.5+)
- haraka: update for renamed uribl plugin
- knot: configure persistent knot dir & shell
> updates to haproxy, haraka, knot

- provision/roundcube.sh
- Create a nginx-owned directory under /tmp and make it use it for its temporary files when TOASTER_USE_TMPFS=1. Helps to minimize jail filesystem writes.
> roundcube: Use /tmp/nginx for nginx temp files when TOASTER_USE_TMPFS=1

- include/php.sh
- mail-toaster.sh
- provision/roundcube.sh
- Allow to set Roundcube product_name setting using ROUNDCUBE_PRODUCT_NAME
Checklist:
> Allow to set Roundcube product_name setting using ROUNDCUBE_PRODUCT_NAME

- mail-toaster.sh
- Fix broken regex substitution in sed_replacement_quote.
> regex typo fix

- provision/clamav.sh
- provision/knot.sh
- provision/mysql.sh
- provision/nagios.sh
- provision/postfix.sh
- clamav: cleaner sed for clamd.conf
- *: install nrpe (4) instead of nrpe3
- mysql: add a couple ZFS optimizations
> Clamav nrpe

- provision/mysql.sh
MariaDB update
- Old MariaDB doesn't exist anymore
-
-
> Update mysql.sh to new MariaDB version

- mail-toaster.sh
- provision/clamav.sh
- provision/mysql.sh
- bump mt.sh version
- clamav: nrpe plugin updates
- mysql: run migrate before starting staged jail
Checklist:
> bump mail-toaster ver

- mail-toaster.sh
- provision/base.sh
- provision/dns.sh
- provision/haraka.sh
- Haraka: install with node 18 (was 16)
- freebsd: add support for ftp-archive.freebsd.org
- dns: tighten up the sed replace in unbound.conf
- dns: configure resolvconf on host
Fixes #557 
Checklist:
> Haraka: install with node 18 (was 16)

- mail-toaster.sh
- provision/bsd_cache.sh
- provision/geoip.sh
- provision/vpopmail.sh
- remove bsd_cache from mt6 build target
- geoip: install node 20 (was 16)
- vpopmail: use single quotes for migration message
Fixes # .
Checklist:
> small build improvements

- provision/base.sh
- provision/borg.sh
- provision/dcc.sh
- provision/geoip.sh
- provision/haproxy.sh
- provision/mail_dmarc.sh
- provision/rsnapshot.sh
- provision/snappymail.sh
- provision/spamassassin.sh
- provision/squirrelcart.sh
- test/mail-toaster.bats
> snappymail: add pecl-xxtea module

- include/linux.sh
- mail-toaster.sh
- provision/bhyve-ubuntu.sh
- provision/centos.sh
- provision/host.sh
- provision/ubuntu.sh
> Linux: add support for jailed Linuxulator & bhyve

- include/mta.sh
- include/mua.sh
- mail-toaster.sh
- provision/dovecot.sh
- mta: improve dma message 
- mua: replace uriencode, add tests
- mt: fix accessing unset var
- mt: skip sleep when no tty
> More changes

- include/shell.sh
- mail-toaster.sh
- provision/mailman.sh
- provision/wildduck.sh
- shell: add set -o vi
- mt: add WILDDUCK_MAIL_DOMAIN & WILDDUCK_HOSTNAME
- mailman: updates
- wildduck: subsume zonemta and haraka into it
> mailman & wildduck

- mail-toaster.sh
- provision/haproxy.sh
- provision/wildduck.sh
> wildduck: fix pools syntax

- provision/host.sh
> host: add ntp alternatives openntpd, chrony

- include/mua.sh
- provision/dovecot.sh
> dovecot: when testing, find an installed curl or install

- include/vpopmail.sh
- provision/dovecot.sh
- provision/vpopmail.sh
> dovecot: add postlogin script to update vpopmail.lastauth

- include/vpopmail.sh
- mail-toaster.sh
- provision/elasticsearch.sh
- provision/haraka.sh
- provision/vpopmail.sh
- vpopmail: update SQL in vmysql.h to be more consistent with source build
- elastic: build config fixes
- haraka: config updates
> vpopmail, haraka, & elastic updates

- provision/roundcube.sh
> roundcube: skip sauserprefs config when SA not installed

- provision/git.sh
- provision/vpopmail.sh
> vpopmail: move lighttpd stuff to /data

- .codeclimate.yml
- mail-toaster.sh
- provision/dns.sh
- provision/host.sh
- provision/unifi.sh
- host: add lo1 description
- mt: remove redundant NIC name in jail.conf.d file
> dns: configure resolvconf, instead of disabling it
